### ISSUE TITLE
bot: Setup bot, list live duels

### ISSUE THREAD

**Issue by rsodre** [underware-gg/pistols-discord-bot#1]
Welcome!

This is the initial kick for making the [Pistols at 10 Blocks](https://github.com/underware-gg/pistols) discord bot a reality!

This repository was cloned from [dojo.js/examples/node/torii-bot](https://github.com/dojoengine/dojo.js/tree/main/examples/node/torii-bot), which is a working implementation of a generic bot that accesses a Dojo game from its Torii server. This example was made by Loaf (@ponderingdemocritus) from the Realms/Dojo team, who is co-hosting this hack and can help if there are any issues.

## Tasks

- [ ] There's a detailed description of how to setup the bot locally on the bot [README](https://github.com/underware-gg/pistols-discord-bot/tree/main/discord-bot)
- [ ] The manifest file required by [dojoConfig.ts](https://github.com/underware-gg/pistols-discord-bot/blob/main/discord-bot/dojoConfig.ts) is here: [manifest.json](https://github.com/underware-gg/pistols/blob/main/client/src/manifest.json). Copy it to `/discord-bot`.
- [ ] Configure the bot to access Pistols at 10 Blocks Slot deployment at: `https://api.cartridge.gg/x/pistols/torii`
- [ ] Create a simple read command: `live_duels`. You must create a GraphQL query that reads the `Challenge` model, where `state = ChallengeState.InProgress`. For now, it is enough to just list the Duel Ids.

The `Challenge` [model](https://github.com/underware-gg/pistols/blob/34f83f6d34c079e8e3d52709fe56472a3176b934/dojo/src/models/models.cairo#L24-L39):
```rust
#[derive(Model, Copy, Drop, Serde)]
struct Challenge {
    #[key]
    duel_id: u128,
    //-------------------------
    duelist_a: ContractAddress, // Challenger
    duelist_b: ContractAddress, // Challenged
    message: felt252,           // message to challenged
    // progress and results
    state: u8,                  // actually a ChallengeState
    round_number: u8,           // current or final
    winner: u8,                 // 0:draw, 1:duelist_a, 2:duelist_b
    // timestamps in unix epoch
    timestamp_start: u64,       // Unix time, started
    timestamp_end: u64,         // Unix time, ended
}
```

- [ ] Create a simple settings json file that can be read by commands
- [ ] Host the bot at a Node server (we can deploy to our CloudFlare account once it's ready)
- [ ] Add the bot to a Discord server (we can provide and configure the server)

## Notes

* Playable deployment: [pistols.lootunder.world](https://pistols.lootunder.world)
* Pistols game source code (Cairo contracts + next.js client): [github.com/underware-gg/pistols](https://github.com/underware-gg/pistols)
* There is a GraphQL [playground](https://api.cartridge.gg/x/pistols/torii/graphql) to test queries
* The bot will query the game using GraphQL. Go to the [Dojo Book](https://book.dojoengine.org/toolchain/torii/graphql) for reference.
* Got questions? Talk to us! If specific about this issue, coding, Pistols, Discord, setup, etc, please comment here. For anything else, go to our [Telegram group](https://t.me/+TziqfXoXkXJiMGFk).

## Requirements

What you need to know to make this happen:

* Node
* Typescript
* GraphQL
* Be fast, as all other issues depend on this one being ready and deployed.

**Comment by Xaxxoo** [comment]
Hi, may I please take this?

**Comment by Ugo-X** [comment]
Good evening @rsodre  please can i be assigned to this? Would love to challenge myself and get this done swiftly

**Comment by rsodre** [comment]
The Hackathon starts on Monday, we will not be assigning or reviewing applications before then to be fair to everyone.

**Comment by Ugo-X** [comment]
> The Hackathon starts on Monday, we will not be assigning or reviewing applications before then to be fair to everyone.

alright chief

**Comment by Ugo-X** [comment]
Hello @rsodre please I'd love to contribute to this effort, can i please be assigned to this?

**Comment by rsodre** [comment]
All good, @Ugo-X ?
If you need something let me know.

**Comment by Ugo-X** [comment]
> All good, @Ugo-X ? If you need something let me know.

alright chief, I am working on it, and if I need anything, I'll be sure to let you know.

**Comment by rsodre** [comment]
cool, for now you can create the bot app on your own discord user
we opened a server for testing, get in there and we give you admin role:
https://discord.gg/YVDqKCgU

**Comment by rsodre** [comment]
btw, I was looking at our bot template and you'll need the game's manifest file
I added a link to it on the issue description

**Comment by Ugo-X** [comment]
alright noted will send a PR immediately i am done

**Comment by Ugo-X** [comment]
<img width="1280" alt="Screenshot 2024-04-23 at 07 59 20" src="https://github.com/underware-gg/pistols-discord-bot/assets/133219527/fa20a790-4145-482d-ab61-83a794238d17">
hi @rsodre 
This is one of the errors ive been hit with following the guide to setup this bot. Please how do i successfully setup thjis repo on my local machine

**Comment by Ugo-X** [comment]
<img width="1280" alt="Screenshot 2024-04-23 at 12 22 51" src="https://github.com/underware-gg/pistols-discord-bot/assets/133219527/ca80879d-b098-4b2f-8788-97afae3da965">

hi @rsodre this is my error trying to set up the discord bot using the setup guide. This has been my block to working on this task

do you think theres a way to combat this, maybe, you can reclone it and see what the issue is.

**Comment by rsodre** [comment]
hey @Ugo-X 

I haven't tried the bot myself, but I think you need to move `dojoConfig.ts` into `/src` to be picked by the compiler.

I've invited @ponderingdemocritus here, he made this template

**Comment by Ugo-X** [comment]
ok. let me try this
or do you think i should wait for his input to avoid any complications

**Comment by rsodre** [comment]
the error looks clear to me, you can try moving that file and see if you can proceed

**Comment by Ugo-X** [comment]
ok then.
let me try that

**Comment by Ugo-X** [comment]
the rootDir here is defined as this 
"rootDir": "/Users/os/Documents/code/dojo.js/example",

and i don't think this is a current location within the repo. I tried changing it to ./src but then it raised 16 new errors about missing files and dependencies

**Comment by rsodre** [comment]
I'll also try to build it here, but I need some time

**Comment by Ugo-X** [comment]
ok chief

**Comment by rsodre** [comment]
hey @Ugo-X 
I added the Pistols manifest and graphql schema, and fixed all typescript build errors
It is now building except for `getMoves`, which should be replaced by our own queries
for this issue, it should become `getChallenges` and access the corresponding`Challenge` model

**Comment by Ugo-X** [comment]
okay chief, let me pull , merge and build

**Comment by rsodre** [comment]
some more info... 
the original bot template is here:
https://github.com/dojoengine/dojo.js/tree/main/examples/node/torii-bot

I think I did something wrong
I replaced our `schema.graphql` for the full torii schema, and it is not necessary
So I think you need to:

* get the original here:
https://github.com/dojoengine/dojo.js/blob/main/examples/node/torii-bot/src/graphql/schema.graphql
* replace `getMoves` for `getChallenges`, from the `challengeModels `
* uncomment `documents` from `codegen.ts`
* run codegen again (see the README)

that should fix everything
I need to go now, catch up later...

**Comment by Ugo-X** [comment]
ok chief. no wonder codegen failed.

**Comment by rsodre** [comment]
This works for `getChallenges.graphql` (replacing `getMoves`)...
(need to uncomment `documents` from `codegen.ts` before generating)

```graphql
query getChallenges($state: u8!) {
    challengeModels(where: { state: $state }) {
        edges {
            node {
                duel_id
                state
            }
        }
    }
}

query getTransations {
    transactions {
        edges {
            node {
                id
                transactionHash
                senderAddress
                calldata
            }
        }
        totalCount
    }
}
```

**Comment by Ugo-X** [comment]
<img width="1280" alt="Screenshot 2024-04-23 at 17 34 31" src="https://github.com/underware-gg/pistols-discord-bot/assets/133219527/ee6343c3-7ee0-4762-9050-c9251d4b7ae9">
<img width="1280" alt="Screenshot 2024-04-23 at 17 34 42" src="https://github.com/underware-gg/pistols-discord-bot/assets/133219527/4063032a-1f91-4f08-8c30-08173fec7bbc">
<img width="1280" alt="Screenshot 2024-04-23 at 17 35 00" src="https://github.com/underware-gg/pistols-discord-bot/assets/133219527/4da07d26-05c6-4fdd-b4b1-ba07e5484005">


I've done the above, but then as seen, codegen exits with an error and the message is something about not seeing a schema file or something
@rsodre , what do you think

**Comment by rsodre** [comment]
Try copying the .env.example to .env again

**Comment by Ugo-X** [comment]
<img width="1280" alt="Screenshot 2024-04-23 at 19 28 12" src="https://github.com/underware-gg/pistols-discord-bot/assets/133219527/a91ed844-3b8d-418a-b65d-d6f96f864b53">

just did, same old error

**Comment by rsodre** [comment]
Should be

TORII_URL=https://api.cartridge.gg/x/pistols/torii
CLIENT_URL=https://pistols.lootunder.world

But anyway its not reading .env on codegen.ts

**Comment by Ugo-X** [comment]
yeah, the problem is the schema, not even the env file
'

**Comment by rsodre** [comment]
Oh... try bun install again

**Comment by Ugo-X** [comment]
i tried running codegen and specifying the schema file but it still didn't cut it.

**Comment by Ugo-X** [comment]
> Oh... try bun install again

ok , give me a minute

**Comment by Ugo-X** [comment]
<img width="1280" alt="Screenshot 2024-04-23 at 19 45 25" src="https://github.com/underware-gg/pistols-discord-bot/assets/133219527/f9b72ada-5275-4a03-b96c-b81b29034551">

bun install done

**Comment by rsodre** [comment]
Dis it generate after bun install?

Codegen.js concatenates TORII_URL with `/graphql`, it looks undefined. You can try replacing the env for the actual url and see if it generates

![image](https://github.com/underware-gg/pistols-discord-bot/assets/229161/1686c11b-626d-43df-af37-83315ab6e18f)

**Comment by Ugo-X** [comment]
hi can we do this? since your own repo runs, can you send me maybe a zip file of it, so i unzip and run just bun install and bun serve. 

cos this seems to be taking too long

**Comment by Ugo-X** [comment]
> Dis it generate after bun install?
> 
> Codegen.js concatenates TORII_URL with `/graphql`, it looks undefined. You can try replacing the env for the actual url and see if it generates
> 
> ![image](https://private-user-images.githubusercontent.com/229161/324959396-1686c11b-626d-43df-af37-83315ab6e18f.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4OTg2NDAsIm5iZiI6MTcxMzg5ODM0MCwicGF0aCI6Ii8yMjkxNjEvMzI0OTU5Mzk2LTE2ODZjMTFiLTYyNmQtNDNkZi1hZjM3LTgzMzE1YWI2ZTE4Zi5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjNUMTg1MjIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTk2NTNlNDJkNmE1ZDBiOGVkNWY3ZDA2NjhmZDVkMGI3MmViNGNiMWZhZDRiNWQ4OTFmZDhmNzYxN2MwYTZkZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.KnbgE1vEQWVcwEMPO8y80ldm7xPUOF5lLrlEbZYFcsY)

let me try this

**Comment by rsodre** [comment]
I'm not at my office now, will be out for a few hours

**Comment by Ugo-X** [comment]
<img width="1280" alt="Screenshot 2024-04-23 at 19 54 48" src="https://github.com/underware-gg/pistols-discord-bot/assets/133219527/7876bd48-ae16-4fea-b9b4-40c927cbbb3a">
just ran. 
codegen successfull

**Comment by Ugo-X** [comment]
<img width="1280" alt="Screenshot 2024-04-23 at 19 58 50" src="https://github.com/underware-gg/pistols-discord-bot/assets/133219527/869af55a-e910-4664-94e7-d9fa204a902c">
i'm already trying to run build

**Comment by Ugo-X** [comment]
<img width="1280" alt="Screenshot 2024-04-23 at 20 05 13" src="https://github.com/underware-gg/pistols-discord-bot/assets/133219527/6b61f2fd-fca6-4e42-924d-6f434ca39da9">


current status

**Comment by Ugo-X** [comment]
<img width="1280" alt="Screenshot 2024-04-23 at 20 17 12" src="https://github.com/underware-gg/pistols-discord-bot/assets/133219527/1b0d4342-fb62-4d6d-aa7a-67aed8c7ca28">


if i understand this file well, i have to import a discord client ( should be from the social app from issue 5) and then import the player_id from the discord client?

i believe i'm in the right direction?

**Comment by rsodre** [comment]
> current status

The argument is `state`, in that case always `InProgress` that can be hard-coded to `5`

https://github.com/underware-gg/pistols/blob/main/dojo/src/types/challenge.cairo

No need to have a player id yet

**Comment by Ugo-X** [comment]
<img width="1280" alt="Screenshot 2024-04-23 at 20 26 05" src="https://github.com/underware-gg/pistols-discord-bot/assets/133219527/de0a5767-8803-4d70-b175-3cfb31afab37">
<img width="1280" alt="Screenshot 2024-04-23 at 20 26 47" src="https://github.com/underware-gg/pistols-discord-bot/assets/133219527/3b6c9f10-45a2-4ced-8d73-d2d4094affc3">


state fixed in , and the sdk wants an annotation. to do that, i might have to change the import method and install '../node_modules/graphql-request/build/esm/types.js'

**Comment by Ugo-X** [comment]
well, let me setup the bot on discord and add it to the server

**Comment by Ugo-X** [comment]
<img width="1280" alt="Screenshot 2024-04-24 at 00 08 49" src="https://github.com/underware-gg/pistols-discord-bot/assets/133219527/eecc9c03-1c66-4d9f-b48f-fdfafcc4c15d">
i am trying to register the bot commands but i'm getting an error even though oi gave the bot all permissions.

i'm working on fixing that now though

**Comment by Ugo-X** [comment]
> <img alt="Screenshot 2024-04-24 at 00 08 49" width="1280" src="https://private-user-images.githubusercontent.com/133219527/325018307-eecc9c03-1c66-4d9f-b48f-fdfafcc4c15d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5MTQxMDUsIm5iZiI6MTcxMzkxMzgwNSwicGF0aCI6Ii8xMzMyMTk1MjcvMzI1MDE4MzA3LWVlY2M5YzAzLTFjNjYtNGQ5Zi1iNDhmLWZkZmFmY2M0YzE1ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyM1QyMzEwMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMzU5ZTIzYjFmODljMWI4MDE3ZGRhY2JmODQxNTQyMzE1ZDg5NjYzZDE4NGVjZjYxZjFmODY5MjEzZjM1ZThkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MiY4ZVNncCMLu3RSnyOeMKKa9a_hub2bW6XRFxx3ztA"> i am trying to register the bot commands but i'm getting an error even though oi gave the bot all permissions.
> i'm working on fixing that now though

also, i think one of our problems is that the .env values are not being read

**Comment by rsodre** [comment]
yes, the problem might be `.env` not reading the credentials

you can try using dotenv

```
bun install dotenv
```

then add to `/src/index.ts` and to `codegen.ts`

```
require('dotenv').config()
```

**Comment by Ugo-X** [comment]
> yes, the problem might be `.env` not reading the credentials
> 
> you can try using dotenv
> 
> ```
> bun install dotenv
> ```
> 
> then add to `/src/index.ts` and to `codegen.ts`
> 
> ```
> require('dotenv').config()
> ```

okay chief, i would do that

**Comment by Ugo-X** [comment]
hi @rsodre 
i'm up now and working on this.
so the current active problem is that the project builds successfully but throws up errors when you are trying to serve the files

i'm trying to find ways to fix this
