### ISSUE TITLE
bot: New Duelists Notification

### ISSUE THREAD

**Issue by rsodre** [underware-gg/pistols-discord-bot#14]
## Tasks

- [x] Implement a WebSocket GraphQL client
- [x] Create a generic GraphQL query for custom events
- [x] Subscribe Torii WebSocket server for new custom events
- [x] When the `DuelistRegistered` event is emitted, send a message to the server with the Duelist profile (same as `duelist` command)
- [ ] Implement a settings option so server admins can enable/disable this notification

## Notes

* The `DuelistRegistered` event key is `0x1afe932323a4032d23a471be00bb333912509b20609983ac2159aa2394f9e5f`
