### ISSUE TITLE
bot: Create my_turn command

### ISSUE THREAD

**Issue by rsodre** [underware-gg/pistols-discord-bot#15]
Depends on #2, #5

## Tasks

- [ ] Create new command: `my_turn`
  - [ ] Check if the Discord User who sent the command is linked to a duelist addresses (#5)
  - [ ] If not, display a message explaining how to link (TBD), and exit
  - [ ] Display a private message to the Discord user, displaying all the Duels that are waiting for their action
  - [ ] The message content must have the same as the `live_duels` (#2) command

The `ChallengeState` [enum](https://github.com/underware-gg/pistols/blob/34f83f6d34c079e8e3d52709fe56472a3176b934/dojo/src/types/challenge.cairo#L4-L14):
```rust
enum ChallengeState {
    Null,
    Awaiting,
    Withdrawn,
    Refused,
    Expired,
    InProgress,
    Resolved,
    Draw,
}
```

## Notes

* Please do not duplicate functionality!
* When displaying a message with the same contents as other messages (`my_duels` and `duels_by_duelist`, `my_turn` and `live_duels` for example), extract the message-building part to a new function that can be called by both.

**Comment by Pycomet** [comment]
@rsodre, this also looks like a great first issue for me. Can I take this on?
