### ISSUE TITLE
bot: Create a settings command

### ISSUE THREAD

**Issue by rsodre** [underware-gg/pistols-discord-bot#17]
## Tasks

- [ ] Create a `settings` command
- [ ] Available only to admins (check some permissions, not role name)
- [ ] Boolean settings for:
  - [ ] new/updated Duelist notifications (#14)
  - [ ] Duels notifications (#4)
  - [ ] Duelist turn notifications (#6)

**Comment by Pycomet** [comment]
Hey @rsodre, this looks like a great first issue for me. Can I take this on?
