### ISSUE TITLE
bot: Duel listing commands

### ISSUE THREAD

**Issue by rsodre** [underware-gg/pistols-discord-bot#2]
After #1 is complete, the `live_duels` command should be listing duel Ids. Let's make it useful!

## Tasks

- [ ] Improve `live_duels` command
  - [ ] Improve GraphQL query, crossing the `Challenge` and `Duelist` models.
  - [ ] Input: `page` (optional)
  - [ ] Display a compact table containing max 10 duels (configurable)
  - [ ] Pagination links, to display [next] 10 Duels (if available) and/or [previous] 10 Duels
  - [ ] Each line display 1 Duel, including:
  * Truncated Duel id (6 first hex) as a link that triggers the `duel` command
  * Wager value using a 💰
  * Current round number
  * Challenger Name, Honour, and 👑 badge (from the `Duelist` model)
  * Challenged Name, Honour, and 👑badge (from the `Duelist` model)
  * If duelists are wounded, display one blood drop 🩸 for each wound by their side
  * Duel elapsed time
- [ ] Create the `duels_by_duelist` command. Exactly like `live_duels`, but filters by duelist (`duelist_a` or `duelist_b`). Please do not to duplicate the whole command, create 2 entry points that generate the same result.
  - [ ] Input: `address`
  - [ ] Input: `page` (optional)
- [ ] Create the `duel` command
  - [ ] Create GraphQL query from the `Duelist` model.
  - [ ] Input: `duel_id`
  - [ ] Display a compact table containing:
  * Truncated Duel id (6 first hex) as a link to the actual duel on the game
  * Challenger Name, Honour, 👑 badge, and square Profile Picture, with link to trigger the `duelist` command
  * Challenged Name, Honour, 👑 badge, and square Profile Picture, with link to trigger the `duelist` command
  * Wager value using a 💰
  * Duel actions so far (see references below)
  * Duel elapsed time

The `Challenge` and `Duelist` [models](https://github.com/underware-gg/pistols/blob/main/dojo/src/models/models.cairo):
```rust
#[derive(Model, Copy, Drop, Serde)]
struct Challenge {
    #[key]
    duel_id: u128,
    //-------------------------
    duelist_a: ContractAddress, // Challenger
    duelist_b: ContractAddress, // Challenged
    message: felt252,           // message to challenged
    // progress and results
    state: u8,                  // actually a ChallengeState
    round_number: u8,           // current or final
    winner: u8,                 // 0:draw, 1:duelist_a, 2:duelist_b
    // timestamps in unix epoch
    timestamp_start: u64,       // Unix time, started
    timestamp_end: u64,         // Unix time, ended
}

#[derive(Model, Copy, Drop, Serde)]
struct Duelist {
    #[key]
    address: ContractAddress,
    //-----------------------
    name: felt252,
    profile_pic: u8,
    total_duels: u16,
    total_wins: u16,
    total_losses: u16,
    total_draws: u16,
    total_honour: u32,  // sum of al duels Honour
    honour: u8,         // +1 decimal, eg: 100 = 10.0
    timestamp: u64,     // Unix time, 1st registered
}
```

## Notes

A little guide for creating new commands...

* Create a new query in `src/graphql/`, similar to `GetChallenges.graphql`
* Create new methods for executing this query `src/queries/`, similar to `getChallenges.ts`
* Create a new command `src/commands/command_name.ts`, similar to `live_duels.ts`
* Be creative and create a beautiful reply using Discord [message embeds](https://discordjs.guide/popular-topics/embeds.html#embed-preview) (see `getChallenges.ts`)

## Reference

* React hooks used in the game client to fetch duels: [useDuel.tsx](https://github.com/underware-gg/pistols/blob/main/client/src/pistols/hooks/useDuel.tsx)
* React hooks used in the game client to fetch duel actions: [useDuelIcons.tsx](https://github.com/underware-gg/pistols/blob/main/client/src/pistols/components/DuelIcons.tsx)

* Profile pictures location (square): 

```js
const url = `${process.env.game_url}/profiles/${duelist.profile_pic}_sq.jpg`
```

* This is the game's [Live Duels ](https://pistols.lootunder.world/tavern)table:

<img width="694" alt="Screenshot 2024-04-20 at 19 44 13" src="https://github.com/underware-gg/pistols-discord-bot/assets/229161/2977588b-d078-40da-ad32-a00b4192babd">

* This is the game's single Duel view:

<img width="892" alt="Screenshot 2024-04-20 at 19 43 53" src="https://github.com/underware-gg/pistols-discord-bot/assets/229161/0dbe2b88-5f12-4bae-8f2a-2f0a0b8c3774">

**Comment by Ugo-X** [comment]
Hello, @rsodre  would love to be part of this effort! thanks (I am on the OD Hack telegram group, ready to start on Monday )

**Comment by Ugo-X** [comment]
Hello, @rsodre would love to be part of this effort!  it's Monday already, thanks

**Comment by Ugo-X** [comment]
@rsodre Good day, i would love to contribute to this effort, please can i be assigned this task?

**Comment by rsodre** [comment]
> @rsodre Good day, i would love to contribute to this effort, please can i be assigned this task?

When #1 is ready ;)

**Comment by Dprof-in-tech** [comment]
Hello @rsodre , its Isaac here. I would love to work on this task
