### ISSUE TITLE
bot: Duelist listing command

### ISSUE THREAD

**Issue by rsodre** [underware-gg/pistols-discord-bot#3]
Depends on #1 

## Tasks

- [ ] Create the `duelist` command
  - [ ] Input: `address`
  - [ ] Create GraphQL query from the `Duelist` model.
  - [ ] Display a compact table containing:
  * Truncated Address (6 first hex) as a link to the actual duelist on the game
  * Duelist Name, Honour, and 👑 badge, if deserving (`duelist.honour > 90`)
  * Display full Profile Picture
  * Duel elapsed time
  * Duels totals
  * Link that triggers the `duels_by_duelist` command (#2)

The `Duelist` [model](https://github.com/underware-gg/pistols/blob/34f83f6d34c079e8e3d52709fe56472a3176b934/dojo/src/models/models.cairo#L7-L20):
```rust
#[derive(Model, Copy, Drop, Serde)]
struct Duelist {
    #[key]
    address: ContractAddress,
    //-----------------------
    name: felt252,
    profile_pic: u8,
    total_duels: u16,
    total_wins: u16,
    total_losses: u16,
    total_draws: u16,
    total_honour: u32,  // sum of al duels Honour
    honour: u8,         // +1 decimal, eg: 100 = 10.0
    timestamp: u64,     // Unix time, 1st registered
}
```

## Notes

A little guide of what needs to be done...

* Create a new query for Duelists `src/graphql/getDuelists.graphql`, similar to `GetChallenges.graphql`
* Create new methods for executing this query `src/queries/getDuelists.ts`, similar to `getChallenges.ts`
* Create a new command `src/commands/duelist.ts`, similar to `live_duels.ts`
* Be creative and create a beautiful duelist profile using Discord [message embeds](https://discordjs.guide/popular-topics/embeds.html#embed-preview) (see `getChallenges.ts`)

## Reference

* Profile pictures location: 
```js
const url = `${process.env.game_url}/profiles/${duelist.profile_pic}_a.jpg`
```

* React hooks used in the game client to fetch duelists: [useDuelist.tsx](https://github.com/underware-gg/pistols/blob/main/client/src/pistols/hooks/useDuelist.tsx)

* This is the game's [Duelist ](https://pistols.lootunder.world/tavern) view:

<img width="892" alt="Screenshot 2024-04-20 at 20 11 55" src="https://github.com/underware-gg/pistols-discord-bot/assets/229161/cdb13095-efae-43c8-b593-2316381550bc">

**Comment by Oshioke-Salaki** [comment]
Please can i be assigned this issue?

**Comment by Oshioke-Salaki** [comment]
Please can i be assigned this issue?

**Comment by gidson5** [comment]
Can I be assigned this task

**Comment by rsodre** [comment]
When dependencies are ready we'll assign this (#1)

**Comment by Ugo-X** [comment]
Please can i be assigned this task?
