### ISSUE TITLE
bot: Challenge Notifications

### ISSUE THREAD

**Issue by rsodre** [underware-gg/pistols-discord-bot#4]
Depends on #14

## Tasks

- [ ] Create a `New Challenge` notification
  - [ ] Create a GraphQL event listener for the `NewChallengeEvent` game event
  - [ ] Send a message to the server similar to the `duel ` command from #2
  - [ ] Message header: **New Challenge**
  - [ ] The message must contain the Duel Id, Challenger name, square Profile Picture, challenge message, and wager value
  - [ ] If the Challenged address exists in the `Duelist` model, the name and profile picture must be shown. If not, use the [unknown duelist pic](https://pistols.lootunder.world/profiles/00_sq.jpg).
- [ ] Create a `Challenge Accepted` notification
  - [ ] Create a GraphQL event listener for the `ChallengeAcceptedEvent` game event
  - [ ] Message header: **Challenge Accepted**
  - [ ] The body of the sent message is the same as the `New Challenge` notification above.
- [ ] Create a command to allow Discord server admins to turn on and off each notification.

Our current [events](https://github.com/underware-gg/pistols/blob/main/dojo/src/types/events.cairo):
```rust
#[derive(Drop, starknet::Event)]
struct NewChallengeEvent {
    duel_id: u128,
    duelist_a: ContractAddress,
    duelist_b: ContractAddress,
}

#[derive(Drop, starknet::Event)]
struct ChallengeAcceptedEvent {
    duel_id: u128,
    duelist_a: ContractAddress,
    duelist_b: ContractAddress,
    accepted: bool,
}
```

The `Challenge` and `Duelist` [models](https://github.com/underware-gg/pistols/blob/main/dojo/src/models/models.cairo):
```rust
#[derive(Model, Copy, Drop, Serde)]
struct Challenge {
    #[key]
    duel_id: u128,
    //-------------------------
    duelist_a: ContractAddress, // Challenger
    duelist_b: ContractAddress, // Challenged
    message: felt252,           // message to challenged
    // progress and results
    state: u8,                  // actually a ChallengeState
    round_number: u8,           // current or final
    winner: u8,                 // 0:draw, 1:duelist_a, 2:duelist_b
    // timestamps in unix epoch
    timestamp_start: u64,       // Unix time, started
    timestamp_end: u64,         // Unix time, ended
}

#[derive(Model, Copy, Drop, Serde)]
struct Duelist {
    #[key]
    address: ContractAddress,
    //-----------------------
    name: felt252,
    profile_pic: u8,
    total_duels: u16,
    total_wins: u16,
    total_losses: u16,
    total_draws: u16,
    total_honour: u32,  // sum of al duels Honour
    honour: u8,         // +1 decimal, eg: 100 = 10.0
    timestamp: u64,     // Unix time, 1st registered
}
```

## Reference

* The `NewChallengeEvent` event key is `0x14a0df74df51e02ef8dedabfd1ea9684ea2087bed6370e881b156d7e2e56975`
* The `ChallengeAcceptedEvent` event key is `0x31cdbf7ac39747303190a727df1a270ae5e4f05191f6f58e452ce4eb1e98abe`
* The [Dojo Book](https://book.dojoengine.org/toolchain/torii/graphql#susbcription-to-events) explains how to create event listeners using GraphQL
* Our friends from [zKorp](https://github.com/z-korp) have a few working [event listeners](https://github.com/z-korp/zconqueror-front/blob/main/src/services/fetchEvents.ts) on their games
