### ISSUE TITLE
bot: Discord Users notifications

### ISSUE THREAD

**Issue by rsodre** [underware-gg/pistols-discord-bot#6]
Depends on #2, #4, #5, #14

## Tasks

- [x] Adapt the `New Challenge ` and `Challenge Accepted` notifications (#4)
  - [x] Check if the Challenge `duelist_a` and `duelist_b` addresses are linked to a Discord User Id (#5)
  - [x] Add a tag to each user to the notifications, when linked
- [ ] Create new events for `Player's Turn`
  - [ ] Create a GraphQL event listener for the `PlayerTurnEvent` game event
  - [ ] Check if the Duelist address is linked to a Discord User Id (#5)
  - [ ] If it is, send a private message to the Discord user
  - [ ] The message content must have the same as the `duel` command (#2)

## Notes

* Please do not duplicate functionality!
* When displaying a message with the same contents as other messages (`Player's Turn` and `duel` for example), extract the message-building part to a new function that can be called by both.
* The `PlayerTurnEvent` event key is `0x19556e1418f1e7a7e6962eff75d1a46abd50bda431139f855ba85c9119754a4`

**Comment by gidson5** [comment]
Hello @rsodre,can I be assigned this task?thanks.

**Comment by gidson5** [comment]
Hello @rsodre,can I be assigned this task?thanks.

**Comment by rsodre** [comment]
we need to wait for the dependencies to be ready before assigning this (#2, #4, #5)

**Comment by stevencartavia** [comment]
Is this issue still unresolved?

**Comment by rsodre** [comment]
> Is this issue still unresolved?

Yes, mostly. It only depends on another internal issue to enable the events in-game.
