### ISSUE TITLE
bot: Link duels command to Discord User, create my_duels command

### ISSUE THREAD

**Issue by rsodre** [underware-gg/pistols-discord-bot#7]
Depends on #2, #5

## Tasks

- [ ] Adapt the `duels_by_duelist ` command (#2)
  - [ ] Allow a special input
  - [ ] Check if the Discord User who sent the command is linked to a duelist addresses (#5)
  - [ ] Check if the Challenge `duelist_a` and `duelist_b` addresses are linked to a Discord User Id (#5)
  - [ ] Add a tag to each user to the notifications, when linked
- [ ] Create the `my_duels` command. Exactly like `live_duels`, but filters by duelist (`duelist_a` or `duelist_b`). Please do not to duplicate the whole command, create 2 entry points that generate the same result.
  - [ ] Check if the Discord User who sent the command is linked to a duelist address (#5)
  - [ ] If not, display a message explaining how to link (TBD), and exit
  - [ ] It must function exactly like the `duels_by_duelist` command (#2)
  - [ ] As `duelist_address`, use the player's duelist addresses linked to their Discord account
  - [ ] Input: `state` as a list of options from the `ChallengeState` enum, used to filter duels
  - [ ] Input: `page` (optional)

The `ChallengeState` [enum](https://github.com/underware-gg/pistols/blob/34f83f6d34c079e8e3d52709fe56472a3176b934/dojo/src/types/challenge.cairo#L4-L14):
```rust
enum ChallengeState {
    Null,
    Awaiting,
    Withdrawn,
    Refused,
    Expired,
    InProgress,
    Resolved,
    Draw,
}
```

## Notes

* Please do not duplicate functionality!
* When displaying a message with the same contents as other messages (`my_duels` and `duels_by_duelist`, `my_turn` and `live_duels` for example), extract the message-building part to a new function that can be called by both.

**Comment by EjembiEmmanuel** [comment]
@rsodre I'd love to work on this if it is still open for contribution

**Comment by Dprof-in-tech** [comment]
hi @rsodre , i would love to work on this issue
